name: Open WebUI
version: 1.0.2
slug: openwebui
description: Home Assistant Open WebUI Add-ons
url: https://github.com/sargo/hassio-open-webui/open-webui
codenotary: wojciech@lichota.pl
init: false
webui: http://[HOST]:[PORT:8080]/
arch:
- aarch64
- amd64
options:
  OPENAI_API_KEY: null
schema:
  OPENAI_API_KEY: str
ports:
  8080/tcp: 8080
startup: services
